---
networks:
  macvlan_network:
    external: true
    name: "${DOCKER_NETWORK}"

services:
  sonarr-setup:
    build: ./build
    image: sonarr-setup
    pull_policy: missing
    container_name: sonarr-setup
    volumes:
      - "${SSL}:/ssl"
      - "${NGINX}:/nginx"
    environment:
      - "ip=${IP_ADDRESS}"

  nginx:
    image: nginx:latest
    pull_policy: always
    container_name: sonarr-nginx
    restart: always
    volumes:
      - "${NGINX}/nginx.conf:/etc/nginx/nginx.conf"
      - "${SSL}:/ssl"
    networks:
      macvlan_network:
        ipv4_address: "${IP_ADDRESS}"
    depends_on:
      sonarr-setup:
        condition: service_completed_successfully

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    pull_policy: always
    container_name: sonarr
    volumes:
      - "${SONARR_CONFIG}:/config"
      - "${MEDIA}:/${ROOT_PATH}"
      - "${DOWNLOADS}:/downloads"
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=${TIMEZONE}"
    restart: always
    network_mode: "service:nginx"
    depends_on:
      qbittorrent:
        condition: service_started

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    pull_policy: always
    container_name: sonarr-qbittorrent
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=${TIMEZONE}"
      - "WEBUI_PORT=8080"
    restart: always
    network_mode: "service:nginx"
    volumes:
      - "${QBITTORRENT_CONFIG}:/config"
      - "${DOWNLOADS}:/downloads"
    depends_on:
      nginx:
        condition: service_started

